# Generated by Django 3.2.5 on 2022-09-16 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('shipType', models.CharField(max_length=240, verbose_name='艦種')),
                ('name', models.CharField(max_length=240, verbose_name='型號')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='價值')),
                ('weight', models.IntegerField(verbose_name='噸位')),
            ],
        ),
    ]
