# Generated by Django 3.2.5 on 2022-09-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='belongsTo',
            field=models.CharField(choices=[('e', '敵軍'), ('a', '我軍')], default=('e', '敵軍'), max_length=1),
        ),
    ]
