# Generated by Django 3.2.5 on 2022-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_ship_belongsto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='sid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='ship',
            name='belongsTo',
            field=models.CharField(choices=[('e', '敵軍'), ('a', '我軍')], default='e', max_length=1),
        ),
    ]
