# Generated by Django 3.2.5 on 2022-09-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0004_ship_defaultweapons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='defaultWeapons',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
