# Generated by Django 3.2.5 on 2022-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0006_alter_ship_defaultweapons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='defaultWeapons',
        ),
        migrations.AddField(
            model_name='ship',
            name='defaultOptions',
            field=models.JSONField(blank=True, default={'weapons': []}),
        ),
    ]
