# Generated by Django 3.2.5 on 2022-09-19 11:44

from django.db import migrations, models
import ships.models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0007_auto_20220919_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='defaultOptions',
        ),
        migrations.AddField(
            model_name='ship',
            name='Options',
            field=models.JSONField(blank=True, default=ships.models.Ship.defaultOptionsTemplate),
        ),
    ]
