# Generated by Django 3.2.5 on 2022-09-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0008_auto_20220919_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='Options',
            new_name='options',
        ),
    ]
