# Generated by Django 3.2.5 on 2022-09-27 07:23

from django.db import migrations, models
import problems.models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_request',
            field=models.JSONField(default=problems.models.Problem.default_problem_request),
        ),
        migrations.AddField(
            model_name='problem',
            name='results',
            field=models.JSONField(default=problems.models.Problem.default_results),
        ),
    ]
