# Generated by Django 3.2.5 on 2022-09-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_timecost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='timeCost',
        ),
    ]
