# Generated by Django 3.2.5 on 2022-09-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_auto_20220918_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='cost',
            field=models.IntegerField(default=100),
        ),
    ]
